### ISSUE TITLE
Provide a Flatpak

### ISSUE THREAD

**Issue by gary-host-laptop** [SeakMengs/WindowPet#1]
Title, basically, also a .rpm would be really good since I'm currently using Fedora, although a flatpak is distro agnostic so that would save some time.

**Comment by SeakMengs** [comment]
Based on what I know, it seems like Tauri doesn't support bundling as flatpak, as mentioned in this [issue](https://github.com/tauri-apps/tauri/issues/3619)

**Comment by gary-host-laptop** [comment]
Oh, I didn't know that, I hope that they add that feature some day then! 

If I create an issue for a .rpm is that something doable?

**Comment by SeakMengs** [comment]
I asked the tauri team on discord and they said their maintainer went insane developing flatpak. About creating an issue for .rpm files, I'm not sure, but someone added support for Arch and RPM using GitHub Actions, as mentioned in the GitHub discussion https://github.com/tauri-apps/tauri/issues/3619#issuecomment-1854688324.
